---
title: "Planktic Fraction Beta Regression"
author: "Yarden Aaltonen"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(brms)
library(ggplot2)
```

## Load Foraminifera Data
```{r load-data}
df <- read_csv("./data-files/mp-files/hm_data.csv")
df <- na.omit(df)
# ensure all values are in (0, 1)
epsilon <- 1e-6
df$planktic_percent <- pmin(pmax(df$planktic_percent, epsilon), 1 - epsilon)
str(df)
```

## Exploratory Plots
```{r exploratory}
ggplot(df, aes(x = planktic_percent)) +
  geom_histogram(binwidth = 0.05, fill = "#6497b1", color = "black") +
  geom_density(alpha = 0.3, color = "#03396c", linewidth = 0.72) +
  facet_wrap(~core) +
  labs(x = "Planktic Fraction", y = "Number of Samples")
```

## Beta Regression
```{r beta-regression}
model <- brm(
  planktic_percent ~ depth + core,
  data = df,
  family = Beta(link = "logit"),
  chains = 4,
  cores = 4,
  iter = 2000,
  seed = 123
  )
```

## Model Summary and Visualization
```{r model-summary}
summary(model)
```

```{r conditional-effects}
conditional_effects(model)
```

```{r posterior-summary}
posterior_summary(model)
```

```{r plot-depth-effect}
ce <- conditional_effects(model)

plot(ce)[[1]] +
  labs(x = "Depth (cm)", y = "Planktic Fraction", title = "Effects of Depth within Core on Planktic Fraction")
```

```{r plot-mean-comparison}
mean_plot <- ce[[2]]

ggplot(mean_plot, aes(x = core, y = estimate__, color = core)) +
  geom_point(size = 3) +
  geom_errorbar(aes(ymin = lower__, ymax = upper__), width = 0.2) +
  labs(x = "Core", y = "Planktic Fraction", title = "Comparison of Mean Planktic Fraction between Cores")
  
```


